// Generated by uniffi-bindgen-react-native
#include "chia-wallet.h"
#include "generated/chia_wallet_sdk_uniffi.hpp"

namespace chiawallet {
	using namespace facebook;

	uint8_t installRustCrate(jsi::Runtime &runtime, std::shared_ptr<react::CallInvoker> callInvoker) {
		NativeChiaWalletSdkUniffi::registerModule(runtime, callInvoker);
		return true;
	}

	uint8_t cleanupRustCrate(jsi::Runtime &runtime) {
		return false;
	}
}