// Generated by uniffi-bindgen-react-native
#ifdef __cplusplus
#import "chia-wallet.h"
#endif

#ifdef RCT_NEW_ARCH_ENABLED
#import "RNChiaWalletSdkSpec.h"

@interface ChiaWallet : NSObject <NativeChiaWalletSpec>
#else
#import <React/RCTBridgeModule.h>

@interface ChiaWallet : NSObject <RCTBridgeModule>
#endif

@end