// Generated by uniffi-bindgen-react-native
import installer from './NativeChiaWallet';

// Register the rust crate with Hermes
installer.installRustCrate();

// Export the generated bindings to the app.
export * from './generated/chia_wallet_sdk_uniffi';

// Now import the bindings so we can:
// - intialize them
// - export them as namespaced objects as the default export.
import * as chia_wallet_sdk_uniffi from './generated/chia_wallet_sdk_uniffi';

// Initialize the generated bindings: mostly checksums, but also callbacks.
chia_wallet_sdk_uniffi.default.initialize();

// Export the crates as individually namespaced objects.
export default {
  chia_wallet_sdk_uniffi,
};

